### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by mwlodarczyk** [pierrelux/rf_pose#1]
Hi,

I would like to use the following code for some experiments regarding the pose estimation on 2D images.

However, as you did not provide any README, I have the following questions:

1. Do you have any trained model that you can share with me?
2. How do you align the training images?
3. How many images are required for efficient training?

Best,
Michal

**Comment by pierrelux** [comment]
Hi Michal, this code was developed in the context of a class projects many years ago. I ended up just using an off-the-shelf random forest implementation (Matlab) and it worked just fine. Nowadays, it's even easier with Scikit Learn which has a good and fast implementation of RF. I will be closing this repo since don't think it can be of any use to anyone.

**Comment by mwlodarczyk** [comment]
Thanks for info!
